server:
  port: 8085

service:
  retry:
    maxretryCount: 3
    retryDelay: 100
 
enrichment:
  retry:
    count: 10
    
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 70000
            
    getValue:
      circuitBreaker:
        requestVolumeThreshold: 20
        sleepWindowInMilliseconds: 50000
        
circuit:
  collapser:
    maxrequestsinbatch: 10
    timerdelayinmilliseconds: 500
                   
spring:
   application:
         name : SampleApp
   
